/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jin Shengxi' at '21-2-19 下午10:16' with Gradle 3.0
 *
 * @author Jin Shengxi, @date 21-2-19 下午10:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
